const SET_DEFAULT_OPTIONS = "SET_DEFAULT_OPTIONS"
const NOTIFY = "NOTIFY"
const REMOVE_NOTIFICATION_BY_ID = "REMOVE_NOTIFICATION_BY_ID"

export {
    SET_DEFAULT_OPTIONS,
    NOTIFY,
    REMOVE_NOTIFICATION_BY_ID
}